### ISSUE TITLE
Help with listings

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/shiny-workshop#3]
@bbest I'm really stumped on this one... I'm trying to create some [listings](https://tbep-tech.github.io/shiny-workshop/resources.html) for the website using the `resources.qmd` file to list files in the resources folder.  I keep getting this warning with Quarto render: 

```
WARNING: File C:\proj\shiny-workshop\resources\tbepwq.qmd in the listing 'list-resources' contains no metadata.
```

The file `tbepwq.qmd` clearly has YAML metadata, so I'm not sure why it's not being read.  The listing appears on the [resources](https://tbep-tech.github.io/shiny-workshop/resources.html) page, but just as a placeholder.  Any idea what's happening?

**Comment by 7yl4r** [comment]
Should `fields` be uncommented in [resources.qmd](https://github.com/tbep-tech/shiny-workshop/blob/main/resources.qmd)?

**Comment by fawda123** [comment]
@7yl4r no, that just defines which parts of the YAML in the content files (the .qmd files in the resources folder) get shown in the grid. https://quarto.org/docs/websites/website-listings.html#listing-fields

**Comment by bbest** [comment]
Hi @fawda123,

The problem seems to be that for a book, the quarto docs (*.qmd) do not get rendered (and therefore somehow not made available for processing) unless specified in the `_quarto.yml`. Whereas, for a website all pages get rendered by default. So forcing that page to render in the `_quarto.yml` (see commit https://github.com/tbep-tech/shiny-workshop/commit/d34d9ab5b7929f21e1c4536bfdd64e803300c4de), gets the page to show. 

## OLD

<img width="454" alt="image" src="https://github.com/tbep-tech/shiny-workshop/assets/2837257/14386d89-5a4c-446b-b58c-7f7995d73107">

## NEW

<img width="264" alt="image" src="https://github.com/tbep-tech/shiny-workshop/assets/2837257/2baf116d-7fb9-4ae7-9cba-2cccc5bcfb88">

**Comment by fawda123** [comment]
Great, thanks @bbest
